local distributionTable = VehicleDistributions[1]

distributionTable["PreETK2400"] = distributionTable["CarNormal"]
distributionTable["PreETK2400i"] = distributionTable["CarNormal"]
distributionTable["PreETK3000i"] = distributionTable["CarNormal"]
distributionTable["PreETK2400ix"] = distributionTable["CarNormal"]
distributionTable["PreETK3000ix"] = distributionTable["CarNormal"]
distributionTable["PreETK2400ti"] = distributionTable["CarNormal"]
distributionTable["PreETK2400tix"] = distributionTable["CarNormal"]
distributionTable["PostETK2400"] = distributionTable["CarNormal"]
distributionTable["PostETK2400i"] = distributionTable["CarNormal"]
distributionTable["PostETK3000i"] = distributionTable["CarNormal"]
distributionTable["PostETK2400ix"] = distributionTable["CarNormal"]
distributionTable["PostETK3000ix"] = distributionTable["CarNormal"]
distributionTable["PostETK2400ti"] = distributionTable["CarNormal"]
distributionTable["PostETK2400tix"] = distributionTable["CarNormal"]
distributionTable["ETK2400tiEvo"] = distributionTable["CarNormal"]
distributionTable["ETK2400tixEvo"] = distributionTable["CarNormal"]