local distributionTable = VehicleDistributions[1]

distributionTable["RoamerI6"] = distributionTable["CarNormal"]
distributionTable["RoamerFossoil"] = distributionTable["PickUpVanLights1"]
distributionTable["RoamerMcCoy"] = distributionTable["PickUpVanMccoy"]
distributionTable["RoamerI64WD"] = distributionTable["CarNormal"]
distributionTable["RoamerV8"] = distributionTable["CarNormal"]
distributionTable["RoamerV84WD"] = distributionTable["CarNormal"]
distributionTable["RoamerRanger"] = distributionTable["PickUpVanLights0"]
distributionTable["RoamerSheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["RoamerXT"] = distributionTable["CarNormal"]
distributionTable["RoamerXT4WD"] = distributionTable["CarNormal"]
distributionTable["RoamerLXT"] = distributionTable["CarNormal"]
distributionTable["RoamerLXT4WD"] = distributionTable["CarNormal"]
distributionTable["RoamerFire"] = distributionTable["PickUpVanLightsFire"]
distributionTable["RoamerRS"] = distributionTable["CarNormal"]
distributionTable["RoamerRSLXT"] = distributionTable["CarNormal"]